export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST'
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS'
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE'

export const EDIT_USER_PROFILE_REQUEST = 'EDIT_USER_PROFILE_REQUEST'
export const EDIT_USER_PROFILE_SUCCESS = 'EDIT_USER_PROFILE_SUCCESS'
export const EDIT_USER_PROFILE_FAILURE = 'EDIT_USER_PROFILE_FAILURE'

export const CLEAR_USER_PROFILE_REQUEST = 'CLEAR_USER_PROFILE_REQUEST'
export const CLEAR_USER_PROFILE_SUCCESS = 'CLEAR_USER_PROFILE_SUCCESS'
export const CLEAR_USER_PROFILE_FAILURE = 'CLEAR_USER_PROFILE_FAILURE'

export const CLEAR_USER_PROFILE_STATE = 'CLEAR_USER_PROFILE_STATE'