export const GET_FOLLOWER_REQUEST = 'GET_FOLLOWER_REQUEST'
export const GET_FOLLOWER_SUCCESS = 'GET_FOLLOWER_SUCCESS'
export const GET_FOLLOWER_FAILURE = 'GET_FOLLOWER_FAILURE'

export const CREATE_FOLLOWER_REQUEST = 'CREATE_FOLLOWER_REQUEST'
export const CREATE_FOLLOWER_SUCCESS = 'CREATE_FOLLOWER_SUCCESS'
export const CREATE_FOLLOWER_FAILURE = 'CREATE_FOLLOWER_FAILURE'

export const FETCH_FOLLOWING_POSTS_REQUEST = "FETCH_FOLLOWING_POSTS_REQUEST";
export const FETCH_FOLLOWING_POSTS_SUCCESS = "FETCH_FOLLOWING_POSTS_SUCCESS";
export const FETCH_FOLLOWING_POSTS_FAILURE = "FETCH_FOLLOWING_POSTS_FAILURE";

export const ADD_CHAT_USER = "ADD_CHAT_USER";
