export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const LOAD_MESSAGES = 'LOAD_MESSAGES';

export const SEND_MESSAGE = "SEND_MESSAGE";
export const SET_MESSAGES = "SET_MESSAGES";

export const MARK_MESSAGES_AS_READ = "MARK_MESSAGES_AS_READ"

export const SET_UNREAD_MESSAGES = "SET_UNREAD_MESSAGES";