export const CREATE_LIKE_REQUEST = 'CREATE_LIKE_REQUEST'
export const CREATE_LIKE_SUCCESS = 'CREATE_LIKE_SUCCESS'
export const CREATE_LIKE_FAILURE = 'CREATE_LIKE_FAILURE'

export const FETCH_LIKE_FAILURE = 'FETCH_LIKE_FAILURE'
export const FETCH_LIKE_SUCCESS = 'FETCH_LIKE_SUCCESS'
export const FETCH_LIKE_REQUEST = 'FETCH_LIKE_REQUEST'

export const SET_LIKES = "SET_LIKES";
export const TOGGLE_LIKE = "TOGGLE_LIKE";
